import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAosrKAuHduP-0IKpVyC1Vjvh6lz30V0Xk&libraries=places&callback=initMap"async></script>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
